### ISSUE TITLE
Waystone Texture Glitch

### ISSUE THREAD

**Issue by Orinai** [Zokonius/planar-artifice#1]
Have noticed a consistently inconsistent bug where the texture of the bottom block portion of the waystone errors out and instead renders as another random texture.

Was actually able to repair the issue on my end by editing the texture to no longer stretch between the top and bottom block, and instead to simply duplicate/tile the texture. Posting here in hopes that helps

**Comment by Orinai** [comment]
In case it helps, I dug back through and found the edited json file for the waystone as I have it in my local version of .13.

https://www.dropbox.com/s/y7z4jivrbd3zuu6/teleporter_bottom.json?dl=0

it uses the same textures , just alters how they are applied, so it should be able to just swap with the existing

**Comment by prodzpod** [comment]
lol @Zokonius close this issue its been fixed for years
