### ISSUE TITLE
Alkimium cannot be molten

### ISSUE THREAD

**Issue by Collecter128** [Zokonius/planar-artifice#10]
I tried to melt alkimium ingots in a smeltery but it says “item cannot be molten”. There are alkimium tools, but I’m not sure how to make them. This mod is super cool though so I hope you can fix it eventually not sure if there is something with the modpack I made causing this or not. https://www.curseforge.com/minecraft/modpacks/collecters-magic-land

**Comment by prodzpod** [comment]
fixed! thanks for letting me know.
