### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by starfish12345** [Zokonius/planar-artifice#13]
[crash-2021-10-12_16.56.57-server.txt](https://github.com/Zokonius/planar-artifice/files/7328629/crash-2021-10-12_16.56.57-server.txt)

**Comment by prodzpod** [comment]
you are using a very old version of planar artifice. try:

- [1.0.1 (curseforge)](https://www.curseforge.com/minecraft/mc-mods/planar-artifice-unofficial/files/3071948)
- [1.1.1 (temporary)](https://github.com/prodzpod/planar-artifice/releases/tag/1.1.1)

**Comment by prodzpod** [comment]
btw @Zokonius please upload 1.1.0 to curseforge lmao
