### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by pibblepower** [Zokonius/planar-artifice#16]
When I loaded up a very large modpack with this mod installed, the game crashed on startup. Here's the crash report:
[crash-2022-02-07_19.10.26-client.txt](https://github.com/Zokonius/planar-artifice/files/8019724/crash-2022-02-07_19.10.26-client.txt)

**Comment by prodzpod** [comment]
theres two mods that add tempus in your mod lol, any ideas?

**Comment by pibblepower** [comment]
I narrowed it down, it's an incompatibility issue with magic bees. Could you fix this next release?
