### ISSUE TITLE
 focal manipulator RGB menu GUI scale issue

### ISSUE THREAD

**Issue by DaRetroCat** [Zokonius/planar-artifice#4]
The RGB menu doesn't scale correctly with other GUI scales expect auto for example using GUI scale large the box completely covers the focus slot and interferes with other parts of the menu

![image](https://user-images.githubusercontent.com/71947170/94350439-435cf700-0003-11eb-898f-d04ce9701ae1.png)

**Comment by prodzpod** [comment]
fixed in one of the new versions btw @Zokonius close this too

**Comment by WindFox** [comment]
I'm still getting this in 1.4.0-pre4
