### ISSUE TITLE
Loadup Bug

### ISSUE THREAD

**Issue by Dayyer1** [Zokonius/planar-artifice#40]
Hello, I had this error when I tried to load an existing world after updating from 1.0.1 to 1.1.6. I think it's PA because I noticed the mention of Spatio in a YABBA barrel, but that's my only guess.
[PA existing world crash 1.txt](https://github.com/Zokonius/planar-artifice/files/8040132/PA.existing.world.crash.1.txt)

Also, I was using Forge 14.23.5.2584. I'll update forge it and update this ticket if there's any changes.

**Comment by prodzpod** [comment]
nah man PA just adds spatio to space related items, its yabba's fault
