### ISSUE TITLE
essentia bug

### ISSUE THREAD

**Issue by KELETU66666** [Zokonius/planar-artifice#43]
![image](https://user-images.githubusercontent.com/92129388/153586321-a9279b36-c1cf-4844-b671-377e14eb9a8d.png)
![image](https://user-images.githubusercontent.com/92129388/153586355-a16eb4d9-c6d4-4c54-b420-bb9e3e13afe2.png)
![image](https://user-images.githubusercontent.com/92129388/153586385-450bf6fc-10a1-4cbc-980b-ee333c7cf7fc.png)
![image](https://user-images.githubusercontent.com/92129388/153586419-5cd080db-3f43-4b57-8cbb-0b9d11c9fb4d.png)

**Comment by prodzpod** [comment]
intended behaviour actually since i didnt touch the vanilla recipes, but ill "fix" them anyways

**Comment by prodzpod** [comment]
wait actually no appearantly thaumcraft just picks them up automatically
how did you managed to make that happen bc its not repro'ing here
give me a modlist

**Comment by KELETU66666** [comment]
> wait actually no appearantly thaumcraft just picks them up automatically how did you managed to make that happen bc its not repro'ing here give me a modlist

It was fixed in version 1.2.0, thanks for your work
