### ISSUE TITLE
Strange Bug

### ISSUE THREAD

**Issue by KELETU66666** [Zokonius/planar-artifice#44]
![image](https://user-images.githubusercontent.com/92129388/153586708-9d099e0b-b9a9-4124-90ff-829ba0a833fb.png)
As shown, I did not install tinkersconstruct, resulting in this empty recipe

**Comment by prodzpod** [comment]
lol i hate when stuff like that happens
its happening because some mods are registering ingotAluminium oredict without actually adding the ore in which ??? bruh

**Comment by KELETU66666** [comment]
> lol i hate when stuff like that happens its happening because some mods are registering ingotAluminium oredict without actually adding the ore in which ??? bruh

Obviously, this is thaumcraft's work,maybe you can add a config to disabled the ore exchange like ingotAluminium or others.

**Comment by prodzpod** [comment]
since 1.2.1, now it checks if the ingot is actually there in addition to the oredict, so it should be fine
