### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Keletu** [Zokonius/planar-artifice#5]
--- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2020-10-01 22:34:35 CST
Description: Ticking block entity

java.lang.RuntimeException: Invalid ticket request
    at net.minecraftforge.common.ForgeChunkManager.requestTicket(ForgeChunkManager.java:741)
    at leppa.planarartifice.tiles.TileTeleporter.update(TileTeleporter.java:86)
    at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
    at net.minecraft.world.World.updateEntities(World.java:1838)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: planarartifice:mirrorteleporter // leppa.planarartifice.tiles.TileTeleporter
  Block type: ID #2364 (tile.teleporter // leppa.planarartifice.blocks.BlockTeleporterMiddle // planarartifice:teleporter)
  Block data value: 0 / 0x0 / 0b0000
  Block location: World: (-1302,69,88), Chunk: (at 10,4,8 in -82,5; contains blocks -1312,0,80 to -1297,255,95), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
  Actual block type: ID #2364 (tile.teleporter // leppa.planarartifice.blocks.BlockTeleporterMiddle // planarartifice:teleporter)
  Actual block data value: 0 / 0x0 / 0b0000
  Block Entity NBT: {lastChangeTime:8592928L,x:-1302,y:69,z:88,id:"planarartifice:mirrorteleporter",inventory:{Size:1,Items:[{Slot:0,id:"thaumcraft:crystal_essence",Count:1b,tag:{Aspects:[{amount:1,key:"terra"}]},Damage:0s}]}}

-- Affected level --
  Level name: 新的世界
  All players: 1 total; [EntityPlayerMP['vxmod'/3324, l='新的世界', x=-1297.92, y=68.00, z=95.88]]
  Chunk stats: ServerChunkCache: 39 Drop: 0
  Level seed: 5342314207972510756
  Level generator: ID 07 - RTG, ver 0. Features enabled: true
  Level generator options: {"seaLevel":63,"useBoulders":true,"boulderMult":1.0,"sandDuneHeight":4,"useSnowLayers":true,"snowLayerTemp":0.12,"bedrockLayers":5,"useCaves":true,"caveChance":10,"caveDensity":7,"useRavines":true,"ravineChance":120,"riverSizeMult":1.0,"riverFrequency":1.0,"riverBendMult":1.0,"riverCutOffAmpl":0.5,"riverCutOffScale":350.0,"RTGlakeSizeMult":1.0,"RTGlakeFreqMult":1.0,"RTGlakeShoreBend":1.0,"useWaterLakes":true,"waterLakeChance":10,"useLavaLakes":true,"lavaLakeChance":80,"useWaterUndLakes":true,"waterUndLakeChance":10,"useLavaUndLakes":true,"lavaUndLakeChance":80,"waterSpoutChance":200,"lavaSpoutChance":200,"useVillages":true,"villageSize":0,"villageDistance":48,"useMineShafts":true,"mineShaftChance":0.004,"useDungeons":true,"dungeonChance":8,"useTemples":true,"templeDistance":48,"useMonuments":true,"monumentSpacing":32,"monumentSeparation":5,"useMansions":true,"mansionSpacing":80,"mansionSeparation":20,"useStrongholds":true,"strongholdCount":128,"strongholdDistance":32,"strongholdSpread":3,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":17,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":128,"ironSize":9,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":64,"goldSize":9,"goldCount":2,"goldMinHeight":0,"goldMaxHeight":32,"redstoneSize":8,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":16,"diamondSize":8,"diamondCount":1,"diamondMinHeight":0,"diamondMaxHeight":16,"lapisSize":7,"lapisCount":1,"lapisCenterHeight":16,"lapisSpread":16}
  Level spawn location: World: (-1238,64,-128), Chunk: (at 10,4,0 in -78,-8; contains blocks -1248,0,-128 to -1233,255,-113), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1)
  Level time: 8688929 game time, 7846659 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 56825 (now: false), thunder time: 2577 (now: true)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_241, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 5848705632 bytes (5577 MB) / 8338276352 bytes (7952 MB) up to 8539602944 bytes (8144 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8129m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 16, tallocated: 121
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 126 mods loaded, 126 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                       | Version                  | Source                                                 | Signature                                |
       |:------ |:------------------------ |:------------------------ |:------------------------------------------------------ |:---------------------------------------- |
       | LCHIJA | minecraft                | 1.12.2                   | minecraft.jar                                          | None                                     |
       | LCHIJA | mcp                      | 9.42                     | minecraft.jar                                          | None                                     |
       | LCHIJA | FML                      | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                    | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | jecharacters             | 1.12.0-3.4.5             | [JEI拼音搜索]JustEnoughCharacters-1.12.0-3.4.5.jar         | None                                     |
       | LCHIJA | smoothfontcore           | mc1.12.2-2.1.1           | minecraft.jar                                          | None                                     |
       | LCHIJA | itemphysic               | 1.4.0                    | minecraft.jar                                          | None                                     |
       | LCHIJA | foamfixcore              | 7.7.4                    | minecraft.jar                                          | None                                     |
       | LCHIJA | smoothfont               | mc1.12.2-2.1.1           | [字体修复]SmoothFont-mc1.12.2-2.1.1.jar                    | None                                     |
       | LCHIJA | uncraftingtable          | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6（分解台）.jar               | None                                     |
       | LCHIJA | inventorytweaks          | 1.63+release.109.220f184 | [R键整理]InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | cucumber                 | 1.1.3                    | [神秘农业前置]Cucumber-1.12.2-1.1.3.jar                      | None                                     |
       | LCHIJA | mysticalagriculture      | 1.7.5                    | [神秘农业]MysticalAgriculture-1.12.2-1.7.5.jar             | None                                     |
       | LCHIJA | mysticalagradditions     | 1.3.2                    | [神秘农业拓展]MysticalAgradditions-1.12.2-1.3.2.jar          | None                                     |
       | LCHIJA | jei                      | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                              | None                                     |
       | LCHIJA | baubles                  | 1.5.2                    | [前置饰品栏]Baubles-1.12-1.5.2.jar                          | None                                     |
       | LCHIJA | thaumcraft               | 6.1.BETA26               | [神秘时代6]Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
       | LCHIJA | ctm                      | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                              | None                                     |
       | LCHIJA | twilightforest           | 3.11.1020                | twilightforest-1.12.2-3.11.1020-universal[1].jar       | None                                     |
       | LCHIJA | immersiveengineering     | 0.12-98                  | [沉浸工艺[与神秘农业联动]ImmersiveEngineering-0.12-98.jar         | None                                     |
       | LCHIJA | mystagradcompat          | 1.2                      | [与沉浸神秘农业联动]mystagradcompat-1.2.jar                     | None                                     |
       | LCHIJA | offlineskins             | 1.12.2-v6                | [中文输入]OfflineSkins-1.12.2-v6.jar                       | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | fbp                      | 2.4.1                    | [优化哦]FancyBlockParticles-1.12.x-2.4.1.jar              | None                                     |
       | LCHIJA | coroutil                 | 1.12.1-1.2.31            | [僵尸意识前置]coroutil-1.12.1-1.2.31.jar                     | None                                     |
       | LCHIJA | zombieawareness          | 1.12.1-1.11.16           | [僵尸意识]zombieawareness-1.12.1-1.11.16.jar               | None                                     |
       | LCHIJA | extendedrenderer         | v1.0                     | [僵尸意识前置]coroutil-1.12.1-1.2.31.jar                     | None                                     |
       | LCHIJA | configmod                | v1.0                     | [僵尸意识前置]coroutil-1.12.1-1.2.31.jar                     | None                                     |
       | LCHIJA | bspkrscore               | 8.0.0                    | [前置][1.12.2]bspkrscore-universal-8.0.1.jar             | None                                     |
       | LCHIJA | forgelin                 | 1.8.4                    | [前置]Forgelin-1.8.4.jar                                 | None                                     |
       | LCHIJA | guideapi                 | 1.12-2.1.8-63            | [前置]Guide-API-1.12.2.jar                               | None                                     |
       | LCHIJA | chunkanimator            | 1.2                      | [区域加载动画]ChunkAnimator-MC1.12-1.2.jar                   | None                                     |
       | LCHIJA | vanillafix               | 1.0.10-SNAPSHOT          | [原版修复]VanillaFix-1.0.10-99.jar                         | None                                     |
       | LCHIJA | recipehandler            | 0.13                     | [合成不冲突]NoMoreRecipeConflict-0.13(1.12.2).jar           | None                                     |
       | LCHIJA | solarflux                | 12.3.8                   | [太阳通量重生]SolarFluxReborn_1.12.2-12.3.8.jar              | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | lostmagic                | 1.0                      | [失落魔法]lostmagic-1.0.1.jar                              | None                                     |
       | LCHIJA | ic2                      | 2.8.1001                 | [工业2经典版[电子神秘工具依附]IC2Classic+1.12-1.5.5.jar             | None                                     |
       | LCHIJA | ic2-classic-spmod        | 0.0.0.0                  | [工业2经典版[电子神秘工具依附]IC2Classic+1.12-1.5.5.jar             | None                                     |
       | LCHIJA | ic2c_extras              | 1.4.5                    | [工业2经典版拓展]IC2CExtras-1.4.5.jar                         | None                                     |
       | LCHIJA | toolbelt                 | 1.9.13                   | [工具皮带]ToolBelt-1.12.2-1.9.13.jar                       | None                                     |
       | LCHIJA | ichunutil                | 7.2.1                    | iChunUtil-1.12.2.jar                                   | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | mobdismemberment         | 7.0.0                    | [怪物肢解]MobDismemberment-1.12.2-7.0.0.jar                | None                                     |
       | LCHIJA | journeymap               | 1.12.2-5.7.1             | [旅行地图]journeymap-1.12.2-5.7.1.jar                      | None                                     |
       | LCHIJA | travelersbackpack        | 1.0.34                   | [旅行背包]TravelersBackpack-1.12.2-1.0.34.jar              | None                                     |
       | LCHIJA | extrautils2              | 1.0                      | [更多实用设备2]extrautils2-1.12-1.9.9.jar                    | None                                     |
       | LCHIJA | botania                  | r1.10-363                | [植物魔法]Botania+r1.10-363.jar                            | None                                     |
       | LCHIJA | moreflowers              | 1.0                      | [更多神秘花]MoreFlowers-1.0.jar                             | None                                     |
       | LCHIJA | ironchest                | 1.12.2-7.0.42.827        | [更多箱子]ironchest-1.12.2-7.0.42.827.jar                  | None                                     |
       | LCHIJA | mysticaladaptations      | 1.8.2                    | [更好的神秘农业]MysticalAdaptations-1.12.2-1.8.2-fix.jar      | None                                     |
       | LCHIJA | versionchecker           | @VERSION@                | [更新检测]VersionChecker-1.4.0.jar                         | None                                     |
       | LCHIJA | theaurorian              | 1.12.2-Release           | [极光密林]theaurorian-1.12.2-release-aug1020.jar           | None                                     |
       | LCHIJA | blur                     | 1.0.4-14                 | [模糊效果]Blur-1.0.4-14.jar                                | None                                     |
       | LCHIJA | keepinginventory         | 2.4                      | [死亡不掉落]KeepingInventory-1.12.2-2.4.jar                 | None                                     |
       | LCHIJA | 113_water_mechanics      | 1.0.2                    | [水力学]WaterMechanicsBackport-1.0.3-1.12.2-NETHERFIX.jar | None                                     |
       | LCHIJA | tc6aspects4jei           | 0.0.2a                   | [水晶JEI拓展]tc6aspects4jei-0.0.2a.jar                     | None                                     |
       | LCHIJA | foamfix                  | 0.10.10-1.12.2           | [泡沫修复]foamfix-0.10.10-1.12.2.jar                       | None                                     |
       | LCHIJA | brazier                  | 1.2.0                    | [源质火盆]brazier-1.2.0.jar                                | None                                     |
       | LCHIJA | thaumcraftjarchecker     | 1.0                      | [源质管子统计]ThaumcraftJarChecker-1.12.2-1.0a.jar           | None                                     |
       | LCHIJA | weisscore                | 0.1.1                    | [电子神秘工具前置]WeissCore-1.12.2-0.1.1-16.jar                | None                                     |
       | LCHIJA | welectromagic            | 0.0.5                    | [电子神秘工具]ElectroMagicToolsIC2C-1.12.2-0.0.5.jar         | None                                     |
       | LCHIJA | customskinloader         | 14.11                    | [皮肤]CustomSkinLoader_Forge-14.11.jar                   | 52885f395e68f42e9b3b629ba56ecf606f7d4269 |
       | LCHIJA | wanionlib                | 1.12.2-2.2               | [矿辞统一前置]WanionLib-1.12.2-2.72.jar                      | None                                     |
       | LCHIJA | thaumicjei               | 1.6.0                    | [神秘6与JEI联动]ThaumicJEI-1.12.2-1.6.0-27.jar              | None                                     |
       | LCHIJA | crimsonwarfare           | 1.5                      | [神秘6拓展]crimsonwarfare-1.5.jar                          | None                                     |
       | LCHIJA | planarartifice           | 1.0                      | [神秘6附属]planarartifice-1.0.0.jar                        | None                                     |
       | LCHIJA | dummycore                | 2.4.112.5.               | [神秘前置]DummyCoreUnofficial-2.4.112.5.jar                | None                                     |
       | LCHIJA | thaumicbases             | 3.3.400.6r               | [神秘基础学]thaumicbases-3.3.352.6r.jar                     | None                                     |
       | LCHIJA | thaumicrestoration       | 1.4.0                    | [神秘复辟]ThaumicRestoration-1.4.0.jar                     | None                                     |
       | LCHIJA | thaumicperiphery         | 0.3.1                    | [神秘外饰]thaumicperiphery-0.3.1.jar                       | None                                     |
       | LCHIJA | thaumicwonders           | 1.8.2                    | [神秘奇境]thaumicwonders-1.8.2.jar                         | None                                     |
       | LCHIJA | tg                       | 0.1.5.0                  | [神秘工具]Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar         | None                                     |
       | LCHIJA | thaumictinkerer          | 1.12.2-5.0-620a0c5       | [神秘工匠]thaumictinkerer-1.12.2-5.0-620a0c5.jar           | None                                     |
       | LCHIJA | thaumicwaila             | 1.12.2-0.0.2             | [神秘拓展]ThaumicWaila-1.12.2-0.0.2.jar                    | None                                     |
       | LCHIJA | appliedenergistics2      | rv6-stable-7             | [神秘能源前置]appliedenergistics2-rv6-stable-7.jar           | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCHIJA | thaumicenergistics       | 2.2.3                    | [神秘能源]thaumicenergistics-2.2.4.jar                     | None                                     |
       | LCHIJA | thaumicaugmentation      | 1.12.2-2.0.7             | [神秘进阶]ThaumicAugmentation-1.12.2-2.0.7.jar             | 8f678591ba6f78d579e553a8aa94b4c4766cb13d |
       | LCHIJA | thaumicbrewing           | 1.0.2                    | [神秘酿造]thaumicbrewing-1.0.2.jar                         | None                                     |
       | LCHIJA | enchantingwiththaumcraft | 1.2                      | [神秘附魔学]enchantingwiththaumcraft-1.2.jar                | None                                     |
       | LCHIJA | hammercore               | 2.0.6.23                 | HammerLib-1.12.2-2.0.6.23.jar                          | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | thaumadditions           | 12.4.3                   | [神秘领域]ThaumicAdditions-1.12.2-12.4.3.jar               | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | neat                     | 1.4-17                   | [简易血条]Neat+1.4-17.jar                                  | None                                     |
       | LCHIJA | armorstatushud           | 1.43.0                   | [耐久显示][1.12]ArmorStatusHUD-client-1.43.0.jar           | None                                     |
       | LCHIJA | i18nmod                  | 1.12.2-1.0.8             | [自动汉化]i18nupdatemod-1.12.2-1.0.8.jar                   | None                                     |
       | LCHIJA | scalingguis              | @VERSION@                | [自定义GUI]scalingguis-1.12.2-1.0.3.0.jar                 | None                                     |
       | LCHIJA | custommainmenu           | 2.0.9.1                  | [自定义主界面]CustomMainMenu-MC1.12.2-2.0.9.1.jar            | None                                     |
       | LCHIJA | waila                    | 1.8.23                   | [采掘信息]Hwyla-1.8.23-B38_1.12.jar                        | None                                     |
       | LCHIJA | wailaharvestability      | 1.1.12                   | [采掘信息]WailaHarvestability-mc1.12-1.1.12.jar            | None                                     |
       | LCHIJA | aroma1997core            | 2.0.0.2                  | [重要前置]Aroma1997Core-1.12.2-2.0.0.2.jar                 | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | LCHIJA | controlling              | 3.0.7                    | [键位冲突显示]Controlling-3.0.7.jar                          | None                                     |
       | LCHIJA | mousetweaks              | 2.10                     | [鼠标手势]MouseTweaks-2.10-mc1.12.2.jar                    | None                                     |
       | LCHIJA | akashictome              | 1.2-12                   | AkashicTome-1.2-12（阿卡什奇书）.jar                          | None                                     |
       | LCHIJA | alembic                  | 1.0.0                    | alembic-1.0.0.jar                                      | None                                     |
       | LCHIJA | appleskin                | 1.0.9                    | AppleSkin-mc1.12-1.0.9（食物信息）.jar                       | None                                     |
       | LCHIJA | attributefix             | 1.0.4                    | AttributeFix-1.12.2-1.0.4（属性修复）.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | autoreglib               | 1.3-32                   | AutoRegLib-1.3-32（前置）.jar                              | None                                     |
       | LCHIJA | forestry                 | 5.8.2.421                | 林业.jar                                                 | None                                     |
       | LCHIJA | binniecore               | 2.5.1.203                | binnie's mods.jar                                      | None                                     |
       | LCHIJA | binniedesign             | 2.5.1.203                | binnie's mods.jar                                      | None                                     |
       | LCHIJA | genetics                 | 2.5.1.203                | binnie's mods.jar                                      | None                                     |
       | LCHIJA | botany                   | 2.5.1.203                | binnie's mods.jar                                      | None                                     |
       | LCHIJA | extrabees                | 2.5.1.203                | binnie's mods.jar                                      | None                                     |
       | LCHIJA | extratrees               | 2.5.1.203                | binnie's mods.jar                                      | None                                     |
       | LCHIJA | bookshelf                | 2.3.590                  | Bookshelf-1.12.2-2.3.590（前置）.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | buildinggadgets          | 2.7.4                    | BuildingGadgets-2.7.4(建筑小工具).jar                       | None                                     |
       | LCHIJA | carryon                  | 1.12.3                   | carryon-1.12.2-1.12.3.15.jar                           | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
       | LCHIJA | chesttransporter         | 2.8.8                    | ChestTransporter-1.12.2-2.8.8（搬箱器）.jar                 | None                                     |
       | LCHIJA | eplus                    | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176（高级附魔台）.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | engineeredgolems         | 1.2                      | Engineered+Golems-1.2a.jar                             | None                                     |
       | LCHIJA | ftblib                   | 5.4.7.2                  | FTBLib-5.4.7.2.jar                                     | None                                     |
       | LCHIJA | itemfilters              | 1.0.4.2                  | ItemFilters-1.0.4.2.jar                                | None                                     |
       | LCHIJA | ftbquests                | 1.9.0.12                 | FTBQuests-1.9.0.12.jar                                 | None                                     |
       | LCHIJA | ftbmoney                 | 1.2.0.47                 | FTBMoney-1.2.0.47.jar                                  | None                                     |
       | LCHIJA | ido                      | 1.0.6                    | ido-1.12.2-1.1.0（游泳）.jar                               | None                                     |
       | LCHIJA | inventoryspam            | 1.0.5                    | InventorySpam-1.12.2-1.0.5（拾取提示）.jar                   | None                                     |
       | LCHIJA | jeibees                  | 0.9.0.5                  | jei林业.jar                                              | None                                     |
       | LCHIJA | quickleafdecay           | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4（树叶腐烂）.jar                | None                                     |
       | LCHIJA | resourceloader           | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3（支持1.12和1.12.1）.jar       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | rustic                   | 1.1.4                    | rustic-1.1.4.jar                                       | None                                     |
       | LCHIJA | rusticthaumaturgy        | 4.4a                     | Rustic+Thaumaturgy-4.4a.jar                            | None                                     |
       | LCHIJA | treechopper              | 1.2.4                    | TreeChopper-1.12.2-1.2.4（砍树）.jar                       | None                                     |
       | LCHIJA | variegated               | 1.2.7                    | variegated-1.2.7.jar                                   | None                                     |
       | LCHIJA | morebees                 | 1.12.2-2.0.1             | 蜜蜂拓展.jar                                               | None                                     |
       | LCHIJA | magicbees                | 1.0                      | 魔法蜜蜂.jar                                               | None                                     |
       | LCHIJA | phosphor-lighting        | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar            | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | rtg                      | 6.1.0.0-snapshot.1       | [真实地形]RTG-1.12.2-6.1.0.0-snapshot.1.jar                | None                                     |
       | LCHIJA | weisscoreterminal        | 0.1.1                    | [电子神秘工具前置]WeissCore-1.12.2-0.1.1-16.jar                | None                                     |
       | LCHIJA | unidict                  | 1.12.2-2.9.5             | [矿辞统一]UniDict-1.12.2-2.9.5.jar                         | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin ([前置]Forgelin-1.8.4.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      JechCore ([JEI拼音搜索]JustEnoughCharacters-1.12.0-3.4.5.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
                                      CustomSkinLoader ([皮肤]CustomSkinLoader_Forge-14.11.jar)
                                        customskinloader.forge.loader.LaunchWrapper
                                      BlurPlugin ([模糊效果]Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      ItemPatchingLoader ([物品物理掉落]ItemPhysic-1.3.7.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      CorePlugin ([字体修复]SmoothFont-mc1.12.2-2.1.1.jar)
                                        bre.smoothfont.asm.Transformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) ([泡沫修复]foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      DCLoadingPlugin ([神秘前置]DummyCoreUnofficial-2.4.112.5.jar)
                                        DummyCore.ASM.DCASMManager
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      offlineskins (OfflineSkins-1.12.2-v6-core.jar)
                                        lain.mods.skins.init.forge.asm.ASMTransformer
                                      VanillaFixLoadingPlugin ([原版修复]VanillaFix-1.0.10-99.jar)
                                        
                                      Thaumic Augmentation Core Plugin ([神秘进阶]ThaumicAugmentation-1.12.2-2.0.7.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      LoadingPlugin ([区域加载动画]ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3（支持1.12和1.12.1）.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      HCASM (HammerLib-1.12.2-2.0.6.23.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      CoreMod ([重要前置]Aroma1997Core-1.12.2-2.0.0.2.jar)
                                        
                                      Inventory Tweaks Coremod ([R键整理]InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  HammerCore Debug Information: Dependent Mods:
                                -Thaumic Additions: Reconstructed (thaumadditions) @ 12.4.3
  [DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore'
  AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
  Suspected Mods: Planar Artifice (planarartifice), Hammer Core (hammercore)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['vxmod'/3324, l='新的世界', x=-1297.92, y=68.00, z=95.88]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by prodzpod** [comment]
This is a known bug - Teleporter was an unfinished feature that came from 0.13. Until this feature is finished I will hide it from JEI - and send a PR to Zoko.

**Comment by Zoko061602** [comment]
The teleporters were actually working I removed an interface in the main mod file which I thought was unused but actually required for it to function.
