### ISSUE TITLE
still getting crash on startup issue with tempus aspect.

### ISSUE THREAD

**Issue by AceTheWildCard** [Zokonius/planar-artifice#58]
still getting the following crash
[crash-2022-02-13_10.32.09-client.txt](https://github.com/Zokonius/planar-artifice/files/8055960/crash-2022-02-13_10.32.09-client.txt)

however, i might have found something related to the issue. thaumicjei has a config file called thaumicjei_itemstack_aspects and so far its the only place i can find that has anything related to the tempus aspect. the following is what is listed:
 {
    "aspect": "Tempus",
    "items": [
      "{id:\"quark:duskbound_lantern\",Count:1s,Damage:0s}",
      "{id:\"charm:ender_pearl_block\",Count:33s,Damage:0s}",
      "{id:\"minecraft:clock\",Count:10s,Damage:0s}",
      "{id:\"minecraft:ender_pearl\",Count:5s,Damage:0s}",
      "{id:\"forestry:engine_clockwork\",Count:7s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"careerbees:eternalframe\",Count:15s,Damage:0s}",
      "{id:\"chickenchunks:chunk_loader\",Count:3s,Damage:1s}",
      "{id:\"extrautils2:ingredients\",Count:3s,Damage:2s}",
      "{id:\"extrautils2:chunkloader\",Count:2s,Damage:0s}",
      "{id:\"extrautils2:grocket\",Count:3s,Damage:3s}",
      "{id:\"extrautils2:grocket\",Count:3s,Damage:4s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"extrautils2:indexerremote\",Count:4s,Damage:0s}",
      "{id:\"extrautils2:klein\",Count:7s,Damage:0s}",
      "{id:\"extrautils2:drum\",Count:10s,Damage:3s}",
      "{id:\"extrautils2:interactionproxy\",Count:15s,Damage:0s}",
      "{id:\"gendustry:genetics_processor\",Count:3s,Damage:0s}",
      "{id:\"randomthings:endermailbox\",Count:7s,Damage:0s}",
      "{id:\"randomthings:entitydetector\",Count:7s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"randomthings:enderletter\",Count:3s,Damage:0s}",
      "{id:\"randomthings:enderbucket\",Count:3s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"randomthings:timeinabottle\",Count:7s,Damage:0s}",
      "{id:\"openblocks:builder_guide\",Count:7s,Damage:0s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:0s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:1s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:2s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:3s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:4s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:5s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:6s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:7s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:8s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:9s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:10s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:11s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:12s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:13s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:14s}",
      "{id:\"openblocks:elevator\",Count:3s,Damage:15s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:1s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:2s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:3s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:4s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:5s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:6s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:7s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:8s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:9s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:10s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:11s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:12s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:13s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:14s}",
      "{id:\"openblocks:elevator_rotating\",Count:2s,Damage:15s}",
      "{id:\"openblocks:generic\",Count:3s,Damage:9s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"openblocks:pedometer\",Count:7s,Damage:0s}",
      "{id:\"thaumadditions:salt_essence\",Count:1s,tag:{Aspects:[{amount:1,key:\"Tempus\"}]},Damage:0s}",
      "{id:\"thaumadditions:vis_pod\",Count:5s,tag:{Aspect:\"Tempus\"},Damage:0s}",
      "{id:\"thaumadditions:crystal_block\",Count:6s,tag:{Aspect:\"Tempus\"},Damage:0s}",
      "{id:\"thaumicbases:endersapling\",Count:7s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"wrcbe:tracker\",Count:3s,Damage:0s}",
      "{id:\"thaumcraft:mirror_essentia\",Count:3s,Damage:0s}",
      "{id:\"appliedenergistics2:wireless_access_point\",Count:1s,Damage:0s}",
      "{id:\"appliedenergistics2:quantum_link\",Count:9s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"appliedenergistics2:wireless_terminal\",Count:1s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"appliedenergistics2:wireless_terminal\",Count:1s,tag:{internalMaxPower:1600000.0d,internalCurrentPower:1600000.0d},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"appliedenergistics2:spatial_storage_cell_16_cubed\",Count:20s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"appliedenergistics2:spatial_storage_cell_128_cubed\",Count:60s,Damage:0s}",
      "{id:\"appliedenergistics2:material\",Count:81s,Damage:34s}",
      "{id:\"appliedenergistics2:material\",Count:27s,Damage:33s}",
      "{id:\"appliedenergistics2:material\",Count:9s,Damage:32s}",
      "{id:\"appliedenergistics2:material\",Count:3s,Damage:9s}",
      "{id:\"appliedenergistics2:material\",Count:2s,Damage:41s}",
      "{id:\"appliedenergistics2:part\",Count:2s,Damage:301s}",
      "{id:\"thaumcraft:crystal_essence\",Count:1s,tag:{Aspects:[{amount:1,key:\"Tempus\"}]},Damage:0s}",
      "{id:\"thaumcraft:phial\",Count:10s,tag:{Aspects:[{amount:10,key:\"Tempus\"}]},Damage:1s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"enderio:item_coord_selector\",Count:3s,Damage:0s}",
      "{id:\"enderio:item_redstone_timer_filter\",Count:7s,Damage:0s}",
      "{id:\"chisel:offsettool\",Count:3s,Damage:0s}",
      "{id:\"ae2wtlib:infinity_booster_card\",Count:1s,Damage:0s}",
      "{id:\"bloodmagic:teleposer\",Count:7s,Damage:0s}",
      "{id:\"conarm:invisible_ink\",Count:3s,Damage:0s}",
      "{id:\"quark:arrow_ender\",Count:3s,Damage:0s}",
      "{id:\"bibliocraft:clock\",Count:7s,Damage:0s}",
      "{id:\"bibliocraft:clock\",Count:7s,Damage:1s}",
      "{id:\"bibliocraft:clock\",Count:7s,Damage:2s}",
      "{id:\"bibliocraft:clock\",Count:7s,Damage:3s}",
      "{id:\"bibliocraft:clock\",Count:7s,Damage:4s}",
      "{id:\"bibliocraft:clock\",Count:7s,Damage:5s}",
      "{id:\"bibliocraft:clock\",Count:7s,Damage:6s}",
      "{id:\"darkutils:timer\",Count:7s,Damage:0s}",
      "{id:\"darkutils:material\",Count:3s,Damage:1s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"darkutils:charm_null\",Count:6s,Damage:0s}",
      "{id:\"endreborn:item_ingot_endorium\",Count:21s,Damage:0s}",
      "{id:\"endreborn:item_raw_endorium\",Count:7s,Damage:0s}",
      "{id:\"endreborn:item_advanced_ender_pearl\",Count:3s,Damage:0s}",
      "{id:\"endreborn:item_end_rune\",Count:3s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:item_world_mirror\",Count:65s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:tool_pickaxe_endorium\",Count:47s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:tool_sword_endorium\",Count:31s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:tool_hoe_endorium\",Count:31s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:tool_axe_endorium\",Count:47s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:tool_shovel_endorium\",Count:15s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:ender_bow\",Count:15s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:ender_sword\",Count:86s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:tool_magnifier\",Count:15s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:entropy_wand\",Count:15s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:armour_chestplate_obsidian\",Count:15s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:armour_leggings_obsidian\",Count:15s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"endreborn:armour_helmet_helmet\",Count:15s,Damage:0s}",
      "{id:\"endreborn:block_rune\",Count:2s,Damage:0s}",
      "{id:\"funkylocomotion:teleporter\",Count:1s,Damage:0s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:0s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:1s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:2s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:3s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:4s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:5s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:6s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:7s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:8s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:9s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:10s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:11s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:12s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:13s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:14s}",
      "{id:\"cfm:digital_clock\",Count:7s,Damage:15s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"gb:gring16\",Count:7s,Damage:0s}",
      "{id:\"gb:end_gring6\",Count:7s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"gb:gring8\",Count:30s,Damage:0s}",
      "{id:\"mysticalagriculture:chunk\",Count:7s,Damage:19s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"rftools:storage_module\",Count:7s,Damage:6s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"rftools:charged_porter\",Count:15s,Damage:0s}",
      "{id:\"rftools:clock_module\",Count:7s,Damage:0s}",
      "{id:\"rftools:slowness_module\",Count:7s,Damage:0s}",
      "{id:\"rftools:remote_storage\",Count:15s,Damage:0s}",
      "{id:\"rftools:matter_transmitter\",Count:11s,Damage:0s}",
      "{id:\"rftools:matter_receiver\",Count:11s,Damage:0s}",
      "{id:\"rftools:destination_analyzer\",Count:15s,Damage:0s}",
      "{id:\"rftools:matter_booster\",Count:11s,Damage:0s}",
      "{id:\"rftools:redstone_transmitter_block\",Count:3s,Damage:0s}",
      "{id:\"rftools:counter_block\",Count:7s,Damage:0s}",
      "{id:\"rftools:timer_block\",Count:7s,Damage:0s}",
      "{id:\"rftools:ender_monitor\",Count:3s,Damage:0s}",
      "{id:\"logisticspipes:pipe_remote_orderer\",Count:3s,Damage:0s}",
      "{id:\"logisticspipes:pipe_inventory_system_connector\",Count:3s,Damage:0s}",
      "{id:\"logisticspipes:pipe_firewall\",Count:3s,Damage:0s}",
      "{id:\"mob_grinding_utils:absorption_upgrade\",Count:15s,Damage:0s}",
      "{id:\"planarartifice:dimensional_singularity\",Count:30s,Damage:0s}",
      "{id:\"xreliquary:mob_charm_fragment\",Count:7s,Damage:8s}",
      "{id:\"rsgauges:automaticswitch4\",Count:7s,Damage:0s}",
      "{id:\"rsgauges:daytimeswitch_glass1\",Count:7s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"tg:pouch_ender\",Count:7s,Damage:0s}",
      "{id:\"tg:book_holder\",Count:15s,Damage:0s}",
      "{id:\"tg:part_stab_1\",Count:15s,Damage:0s}",
      "{id:\"tg:teleportator_core\",Count:15s,Damage:0s}",
      "{id:\"tg:teleportator_frame\",Count:1s,Damage:0s}",
      "{id:\"tg:teleportator_floor\",Count:2s,Damage:0s}",
      "{id:\"torchmaster:frozen_pearl\",Count:3s,Damage:0s}",
      "{id:\"actuallyadditions:block_player_interface\",Count:56s,Damage:0s}",
      "{id:\"actuallyadditions:block_ranged_collector\",Count:7s,Damage:0s}",
      "{id:\"actuallyadditions:block_phantomface\",Count:11s,Damage:0s}",
      "{id:\"actuallyadditions:block_phantom_placer\",Count:8s,Damage:0s}",
      "{id:\"actuallyadditions:block_phantom_liquiface\",Count:8s,Damage:0s}",
      "{id:\"actuallyadditions:block_phantom_energyface\",Count:8s,Damage:0s}",
      "{id:\"actuallyadditions:block_phantom_redstoneface\",Count:8s,Damage:0s}",
      "{id:\"actuallyadditions:block_phantom_breaker\",Count:8s,Damage:0s}",
      "{id:\"actuallyadditions:block_misc\",Count:15s,Damage:6s}",
      "{id:\"actuallyadditions:block_misc\",Count:15s,Damage:8s}",
      "{id:\"actuallyadditions:block_item_repairer\",Count:11s,Damage:0s}",
      "{id:\"actuallyadditions:block_phantom_booster\",Count:11s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"actuallyadditions:item_void_bag\",Count:3s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"actuallyadditions:item_tele_staff\",Count:33s,tag:{Energy:250000},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"actuallyadditions:item_tele_staff\",Count:33s,tag:{Energy:0},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"actuallyadditions:item_drill_upgrade_fortune_ii\",Count:11s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"actuallyadditions:item_phantom_connector\",Count:7s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"cyclicmagic:book_ender\",Count:26s,tag:{},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"cyclicmagic:ender_dungeon\",Count:3s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"astralsorcery:itemwand\",Count:3s,tag:{astralsorcery:{}},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"astralsorcery:itemwand\",Count:3s,tag:{astralsorcery:{AugmentName:\"astralsorcery.constellation.aevitas\"}},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"astralsorcery:itemwand\",Count:3s,tag:{astralsorcery:{AugmentName:\"astralsorcery.constellation.discidia\"}},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"astralsorcery:itemwand\",Count:3s,tag:{astralsorcery:{AugmentName:\"astralsorcery.constellation.vicio\"}},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"astralsorcery:itemwand\",Count:3s,tag:{astralsorcery:{AugmentName:\"astralsorcery.constellation.armara\"}},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"astralsorcery:itemwand\",Count:3s,tag:{astralsorcery:{AugmentName:\"astralsorcery.constellation.evorsio\"}},Damage:0s}",
      "{id:\"computercraft:peripheral\",Count:3s,Damage:1s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"computercraft:pocket_computer\",Count:2s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"computercraft:pocket_computer\",Count:2s,tag:{upgrade:\"computercraft:wireless_modem\"},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"computercraft:pocket_computer\",Count:2s,tag:{upgrade:\"computercraft:advanved_modem\"},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"computercraft:pocket_computer\",Count:2s,tag:{upgrade:\"computercraft:speaker\"},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"computercraft:pocket_computer\",Count:2s,Damage:1s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"computercraft:pocket_computer\",Count:2s,tag:{upgrade:\"computercraft:wireless_modem\"},Damage:1s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"computercraft:pocket_computer\",Count:2s,tag:{upgrade:\"computercraft:advanved_modem\"},Damage:1s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"computercraft:pocket_computer\",Count:2s,tag:{upgrade:\"computercraft:speaker\"},Damage:1s}",
      "{id:\"portalgun:item_dust_ender_pearl\",Count:3s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"portalgun:item_miniature_black_hole\",Count:18s,Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"portalgun:item_portalgun\",Count:13s,tag:{lastFired:1b,width:1,channelName:\"Chell\",grabStrength:4,uuid:\"Global\",username:\"Global\",height:2},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"portalgun:item_portalgun\",Count:13s,tag:{lastFired:1b,width:1,channelName:\"Atlas\",grabStrength:4,uuid:\"Global\",username:\"Global\",height:2},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"portalgun:item_portalgun\",Count:13s,tag:{lastFired:1b,width:1,channelName:\"P-body\",grabStrength:4,uuid:\"Global\",username:\"Global\",height:2},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"portalgun:item_portalgun\",Count:13s,tag:{lastFired:1b,width:1,channelName:\"Creative Inventory\",grabStrength:4,uuid:\"5aaf7c295a474cd38018a458d47991df\",username:\"AceTheWildCard\",height:2},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"portalgun:item_portalgun\",Count:13s,tag:{lastFired:1b,width:1,channelName:\"Creative Inventory Type #2\",grabStrength:4,uuid:\"5aaf7c295a474cd38018a458d47991df\",username:\"AceTheWildCard\",height:2},Damage:0s}",
      "{ForgeCaps:{\"astralsorcery:cap_item_amulet_holder\":{}},id:\"portalgun:item_portalgun\",Count:13s,tag:{lastFired:1b,width:1,channelName:\"Creative Inventory Type #3\",grabStrength:4,uuid:\"5aaf7c295a474cd38018a458d47991df\",username:\"AceTheWildCard\",height:2},Damage:0s}",
      "{id:\"ebwizardry:spell_book\",Count:3s,Damage:116s}",
      "{id:\"ebwizardry:spell_book\",Count:3s,Damage:38s}",
      "{id:\"ebwizardry:spell_book\",Count:3s,Damage:84s}",
      "{id:\"rftools:storage_terminal\",Count:7s,Damage:0s}"
    ]
  },

the file is in JSON format and is fairly large in size, so i cannot post the file itself.

**Comment by AceTheWildCard** [comment]
right so i removed magic bees and ive gotten past the point where it crashes trying to start up. it might be something in my configs, but im not sure which one. any ideas?

**Comment by prodzpod** [comment]
reinstall magic bees, remove the thaumic jei json file, retry. see if it crashes

**Comment by AceTheWildCard** [comment]
i will do that in the morning.

**Comment by AceTheWildCard** [comment]
still crashing with the same crash
[crash-2022-02-14_09.36.51-client.txt](https://github.com/Zokonius/planar-artifice/files/8061599/crash-2022-02-14_09.36.51-client.txt)

**Comment by prodzpod** [comment]
okay, i have literally re-downloaded your entire modlist by individually downloading all mods shown in the crash log, it doesn't crash. I genuinely don't know what's the problem here then.

**Comment by AceTheWildCard** [comment]
strange... well, if other people come forward with this issue then maybe it can be solved in the future. for now ill just not use magic bees. just keep in mind this is a potentially rare issue

**Comment by prodzpod** [comment]
this is definitely a rare issue. crazy to say but i think this is neither magic bees or PA's fault. magic bees definitely has Tempus. something is forcing magic bees to unload tempus for some reason.
