### ISSUE TITLE
Enhanced Aspect and Foci Icons

### ISSUE THREAD

**Issue by Turkey9002** [Zokonius/planar-artifice#67]
I noticed the strange quality of the foci and aspect icons when compared to Thaumcraft and other mods of similar quality like Thaumic Augmentation so I fixed them up by resizing them from the website they were taken from. (Game-icons.net)

Tinctura was more interesting because it was two icons put together. I wasn't sure if it turned out as well but I also made an alternate version with just the paintbrush if that's more preferable. Hope it helps! ^^

[icons.zip](https://github.com/Zokonius/planar-artifice/files/8101310/icons.zip)

**Comment by prodzpod** [comment]
wow yeah i tried to emulate the thaum style but failed spectacularly, thank you for your contribution, will push with the next update
