### ISSUE TITLE
crash pls help :/ <3

### ISSUE THREAD

**Issue by dankdan02** [Zokonius/planar-artifice#68]
updated from 1.3.4 to 1.3.99 and got this crash on startup. :/
[crash-2022-02-18_22.18.39-client.txt](https://github.com/Zokonius/planar-artifice/files/8101428/crash-2022-02-18_22.18.39-client.txt)

**Comment by dankdan02** [comment]
thinking maybe something to do with the support of certain mods if there installed or not, idk sir what do you think? <3

**Comment by prodzpod** [comment]
yes we know, i just fixed it

**Comment by dankdan02** [comment]
thank you king
