### ISSUE TITLE
creash with the latest version 1.3.999

### ISSUE THREAD

**Issue by Biviho** [Zokonius/planar-artifice#70]
game crash on startup

the crashlog: [link](https://pastebin.com/XdDNPLeP)

**Comment by prodzpod** [comment]
oh i love tinkers

**Comment by prodzpod** [comment]
fixed

**Comment by Biviho** [comment]
for curiosity, what happened?

**Comment by prodzpod** [comment]
tinkers have this "pulse" system that ?????? splits up the mod into multiple pieces ??? and needs to be checked before accessing??? idk its a thing
