### ISSUE TITLE
Research not appearing in Thaumonomicon

### ISSUE THREAD

**Issue by Orinai** [Zokonius/planar-artifice#8]
For whatever reason, in the most recent version nont of the research entries show up in the thaumonomicon. the tab is there, but even with the cheater's thaumonomicon, it is empty

**Comment by Alyssalove27** [comment]
I had the same problem... reverted to 1.0.0 and it works.

Although 1.0.0 doesn't work on a dedicated server... so I had to go singleplayer, cheat in the research tab, screenshot the recipes, then go back to 1.0.1 to play.

So yeah it's only the research tab missing!

**Comment by prodzpod** [comment]
research works now! epic
